### ISSUE TITLE
Error on executing ark

### ISSUE THREAD

**Issue by Lechucico** [sous-chefs/ark#200]
Cookbook version: 3.1.0

Code:

```
yum_package 'unzip' do
	action :install
end

yum_package 'rsync' do
	action :install
end

ark 'vault' do
	url 'https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip'
end
```

Error:
```
================================================================================
             Error executing action `run` on resource 'execute[unpack /tmp/kitchen/cache/vault-1.zip]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '23'
             ---- Begin output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
             STDOUT:
             STDERR: rsync: change_dir "/tmp/d20171106-4097-1y9cd0e/*" failed: No such file or directory (2)
             rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
             ---- End output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
             Ran unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e returned 23

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/ark/resources/default.rb

       72:   execute "unpack #{new_resource.release_file}" do
       73:     command unpack_command
       74:     cwd new_resource.path
       75:     environment new_resource.environment
       76:     notifies :run, "execute[set owner on #{new_resource.path}]"
       77:     action :nothing
       78:   end
       79:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/ark/resources/default.rb:72:in `block in class_from_file'

             execute("unpack /tmp/kitchen/cache/vault-1.zip") do
        action [:nothing]
        default_guard_interpreter :execute
        command "unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e"
        backup 5
        cwd "/usr/local/vault-1"
        returns 0
        user nil
        declared_type :execute
        cookbook_name "living-vault-cli"
        domain nil
             end

             System Info:
             ------------
             chef_version=13.6.0
             platform=centos
             platform_version=7.3.1611
             ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
             program_name=chef-client worker: ppid=4092;start=11:43:22;
             executable=/opt/chef/bin/chef-client


           ================================================================================
           Error executing action `install` on resource 'ark[vault]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[unpack /tmp/kitchen/cache/vault-1.zip] (/tmp/kitchen/cache/cookbooks/ark/resources/default.rb line 72) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '23'
           ---- Begin output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
           STDOUT:
           STDERR: rsync: change_dir "/tmp/d20171106-4097-1y9cd0e/*" failed: No such file or directory (2)
           rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
           ---- End output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
           Ran unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e returned 23

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/living-vault-cli/recipes/default.rb

            15: ark 'vault' do
            16:         url 'https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip'
            17: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/living-vault-cli/recipes/default.rb:15:in `from_file'

           ark("vault") do
             action [:install]
             updated true
             updated_by_last_action true
             default_guard_interpreter :default
             declared_type :ark
             cookbook_name "living-vault-cli"
             recipe_name "default"
             url "https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip"
             extension "zip"
             prefix_bin "/usr/local/bin"
             prefix_root "/usr/local"
             home_dir "/usr/local/vault"
             version "1"
             owner "root"
             path "/usr/local/vault-1"
             release_file "/tmp/kitchen/cache/vault-1.zip"
           end

           System Info:
           ------------
           chef_version=13.6.0
           platform=centos
           platform_version=7.3.1611
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=4092;start=11:43:22;
           executable=/opt/chef/bin/chef-client


       Running handlers:
       [2017-11-06T11:43:51+00:00] ERROR: Running exception handlers
       [2017-11-06T11:43:51+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-11-06T11:43:51+00:00] ERROR: Exception handlers complete
       [2017-11-06T11:43:51+00:00] ERROR: Exception handlers complete
       Chef Client failed. 5 resources updated in 28 seconds
       [2017-11-06T11:43:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-11-06T11:43:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-11-06T11:43:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-11-06T11:43:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-11-06T11:43:51+00:00] ERROR: ark[vault] (living-vault-cli::default line 15) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[unpack /tmp/kitchen/cache/vault-1.zip] (/tmp/kitchen/cache/cookbooks/ark/resources/default.rb line 72) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '23'
       ---- Begin output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
       STDOUT:
       STDERR: rsync: change_dir "/tmp/d20171106-4097-1y9cd0e/*" failed: No such file or directory (2)
       rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
       ---- End output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
       Ran unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e returned 23
       [2017-11-06T11:43:51+00:00] ERROR: ark[vault] (living-vault-cli::default line 15) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[unpack /tmp/kitchen/cache/vault-1.zip] (/tmp/kitchen/cache/cookbooks/ark/resources/default.rb line 72) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '23'
       ---- Begin output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
       STDOUT:
       STDERR: rsync: change_dir "/tmp/d20171106-4097-1y9cd0e/*" failed: No such file or directory (2)
       rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
       ---- End output of unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e ----
       Ran unzip -q -o /tmp/kitchen/cache/vault-1.zip -d /tmp/d20171106-4097-1y9cd0e && rsync -a /tmp/d20171106-4097-1y9cd0e/*/ /usr/local/vault-1 && rm -rf /tmp/d20171106-4097-1y9cd0e returned 23
       [2017-11-06T11:43:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-11-06T11:43:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by greglu** [comment]
It seems like by default, ark assumes the zip files will extract under a leading directory, so it adds in the `/*` portion to the rsync command. You can fix your resource with the `strip_components` parameter:

```ruby
ark 'vault' do
	url 'https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip'
	strip_components 0
end
```
